modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/Hantonik/AnvilAPI/issues"

[[mods]]
    modId="anvilapi"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/anvilapi"
    logoFile="logo.png"
    updateJSONURL="https://raw.githubusercontent.com/Hantonik/AnvilAPI/${mc_version}/update.json"
    authors="Hantonik"
    description='''AnvilAPI adds to the game the ability to create custom anvil recipes by datapacks.'''

[[dependencies.anvilapi]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.anvilapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
