modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Hantonik/AnvilAPI/issues"

[[mods]]
    modId="anvilapi"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/anvilapi"
    logoFile="logo.png"
    updateJSONURL="https://raw.githubusercontent.com/Hantonik/AnvilAPI/1.20/update.json"
    authors="Hantonik"
    description='''AnvilAPI adds to the game the ability to create custom anvil recipes by datapacks.
'''

[[dependencies.anvilapi]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.anvilapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
