name: 'Build'

on: [push, workflow_call]

permissions:
  contents: read
  statuses: write

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'

      - name: 'Build with Gradle'
        run: ./gradlew build

      - name: 'Move artifacts'
        shell: bash
        run: |
          mkdir artifacts
          cp Fabric/build/libs/*.jar artifacts
          cp Forge/build/libs/*.jar artifacts
          cp NeoForge/build/libs/*.jar artifacts

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: artifacts/*