name: 'Publish'

on:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 'Build'
        uses: ./.github/workflows/build.yml

      - name: 'Generate changelog with Gradle'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: makeChangelog
          cache-read-only: false

      - name: 'Publish mod with Gradle'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishMod
          cache-read-only: false
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}