name: 'Publish'

on:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  pre-publish:
    name: 'Pre-publish'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'

      - name: 'Generate Changelog'
        run: ./gradlew makeChangelog

      - uses: ./.github/actions/build
  publish:
    name: 'Publish'
    needs: ['pre-publish']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'

      - name: 'Publish'
        run: ./gradlew publishMod
        env:
          CURSEFORGE_TOKEN: ${{secrets.CURSEFORGE_TOKEN}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}